---

- name: (mysql_install) [2/5] MariaDB repo is added
  yum_repository:
    name: mariadb
    description: MariaDB repo
    baseurl: http://yum.mariadb.org/{{ mysql_mariadb_version }}/centos7-$basearch/
    file: external_repos
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    enabled: yes
  when: mysql_mariadb_version != 5.5

- name: (mysql_install) [1/4] MySQL/MariaDB packages are installed and the latest version
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    # These need this specific capitalization
    - MariaDB-server
    - MariaDB-client
    - MySQL-python

- name: (mysql_install) [2/4] MariaDB enabled on boot
  service:
    name: mariadb
    state: started
    enabled: yes

- name: (mysql_install) [3/4] MySQL database {{ mysql_dbname }} is present
  mysql_db:
    name: "{{ mysql_dbname }}"
    state: present

- name: (mysql_install) [4/4] MySQL database account {{ mysql_dbuser }} is present for database {{ mysql_dbname }}
  mysql_user:
    name: "{{ mysql_dbuser }}"
    password: "{{ mysql_dbpasswd }}"
    priv: "{{ mysql_dbname }}.*:ALL,GRANT"
    state: present
