---

- name: (mysql_config) [1/3] Template {{ mysql_database }}.sql is deployed
  template:
    src: ../templates/{{ mysql_database }}.sql.j2
    dest: /tmp/database.sql

- name: (mysql_config) [2/3] Database populated with data
  mysql_db:
    name: "{{ mysql_dbname }}"
    state: import
    target: /tmp/database.sql
  notify: Restart mariadb

- name: (mysql_config) [3/3] File {{ mysql_database }}.sql is dispelled
  file:
    path: /tmp/database.sql
    state: absent
